# =============================================================================
# JacobPEvans Standard Labels
# =============================================================================
# Canonical label set for all repositories.
# Synced via EndBug/label-sync GitHub Action.
#
# Categories:
#   type:*     - What kind of change (aligns with semantic versioning)
#   priority:* - Urgency level
#   size:*     - Effort estimation
#   ai:*       - AI workflow state
#   (ungrouped) - Triage/admin labels
#
# Requirements (enforced via issue templates):
#   - At least one type:* label
#   - Exactly one priority:* label
#   - Exactly one size:* label
# =============================================================================

# =============================================================================
# TYPE LABELS - What kind of change is this? (Categorical, distinct colors)
# Each type has a unique color for easy visual identification. No overlap with priority/size.
# =============================================================================
- name: "type:bug"
  color: "DC2626"
  description: "Bug - Something isn't working (semver: PATCH)"

- name: "type:feature"
  color: "3B82F6"
  description: "Feature - New feature or request (semver: MINOR)"

- name: "type:breaking"
  color: "7C2D12"
  description: "Breaking - Breaking changes (semver: MAJOR)"

- name: "type:docs"
  color: "8B5CF6"
  description: "Docs - Documentation only changes"

- name: "type:chore"
  color: "64748B"
  description: "Chore - Maintenance tasks, dependencies, tooling"

- name: "type:ci"
  color: "0EA5E9"
  description: "CI - CI/CD pipeline changes"

- name: "type:test"
  color: "22C55E"
  description: "Test - Adding or correcting tests"

- name: "type:refactor"
  color: "EAB308"
  description: "Refactor - Code change with no functional change"

- name: "type:perf"
  color: "F97316"
  description: "Perf - Performance improvements"

# =============================================================================
# PRIORITY LABELS - How urgent is this? (Heat map: Red → Orange → Yellow → Green)
# Critical = hot red, Low = cool green (intuitive urgency indicator)
# =============================================================================
- name: "priority:critical"
  color: "B91C1C"
  description: "Critical - Requires immediate attention (semver: emergency)"

- name: "priority:high"
  color: "EA580C"
  description: "High - Should be addressed soon (semver: priority)"

- name: "priority:medium"
  color: "F59E0B"
  description: "Medium - Normal workflow (semver: standard)"

- name: "priority:low"
  color: "059669"
  description: "Low - Address when time permits (semver: backlog)"

# =============================================================================
# SIZE LABELS - How much effort is this? (Green intensity: Light → Dark)
# XS = very light, XL = dark (effort intensity gradient)
# =============================================================================
- name: "size:xs"
  color: "D1FAE5"
  description: "XS - Trivial change, <1 hour"

- name: "size:s"
  color: "A7F3D0"
  description: "S - Simple change, 1-4 hours"

- name: "size:m"
  color: "6EE7B7"
  description: "M - Moderate effort, 1-2 days"

- name: "size:l"
  color: "34D399"
  description: "L - Significant work, 3-5 days"

- name: "size:xl"
  color: "047857"
  description: "XL - Major effort, 1+ weeks"

# =============================================================================
# WORKFLOW LABELS - Issue and PR lifecycle management
# =============================================================================
- name: "ready-for-dev"
  color: "10B981"
  description: "Ready - Shaped, requirements clear, ready for development"

- name: "good-first-issue"
  color: "7C3AED"
  description: "Good for newcomers - Well-scoped, documented, beginner-friendly"

- name: "ai:created"
  color: "FCD34D"
  description: "AI-generated - Requires human approval before implementation"

- name: "ai:ready"
  color: "06B6D4"
  description: "AI-ready - Human-approved and ready for AI agent implementation"

# -----------------------------------------------------------------------------
# TRIAGE LABELS - Administrative
# -----------------------------------------------------------------------------
- name: "duplicate"
  color: "CBD5E1"
  description: "Duplicate - This issue or pull request already exists"

- name: "invalid"
  color: "FDE047"
  description: "Invalid - This doesn't seem right"

- name: "wontfix"
  color: "FFFFFF"
  description: "Wontfix - This will not be worked on"

- name: "question"
  color: "E879F9"
  description: "Question - Further information is requested"

# =============================================================================
# DEPRECATED LABELS - Keep for migration tracking
# =============================================================================
# Legacy labels (DEPRECATED - keep for migration)
# Legacy labels (DEPRECATED - keep for migration)
- name: "bug"
  color: "d73a4a"
  description: "DEPRECATED: Use 'type:bug' instead"

- name: "enhancement"
  color: "a2eeef"
  description: "DEPRECATED: Use 'type:feature' instead"

- name: "documentation"
  color: "0075ca"
  description: "DEPRECATED: Use 'type:docs' instead"

- name: "priority: critical"
  color: "b60205"
  description: "DEPRECATED: Use 'priority:critical' instead"

- name: "priority: high"
  color: "d93f0b"
  description: "DEPRECATED: Use 'priority:high' instead"

- name: "priority: medium"
  color: "fbca04"
  description: "DEPRECATED: Use 'priority:medium' instead"

- name: "priority: low"
  color: "0e8a16"
  description: "DEPRECATED: Use 'priority:low' instead"

- name: "good first issue"
  color: "7057ff"
  description: "DEPRECATED: Use 'good-first-issue' instead"

- name: "help wanted"
  color: "008672"
  description: "DEPRECATED: Use 'help-wanted' instead"

- name: "timebox:small-batch"
  color: "00ff00"
  description: "DEPRECATED: Use 'size:s' or 'size:m' instead"

- name: "timebox:big-batch"
  color: "ff9900"
  description: "DEPRECATED: Use 'size:l' or 'size:xl' instead"

- name: "timebox:spike"
  color: "9933ff"
  description: "DEPRECATED: Use 'size:xs' for research spikes"
