name: Claude Code Review (Reusable)

on:
  workflow_call:
    inputs:
      max-turns:
        description: 'Maximum turns for Claude Code'
        required: false
        type: number
        default: 5
      timeout-minutes:
        description: 'Timeout for the Claude Code action'
        required: false
        type: number
        default: 5
      check-comment-limit:
        description: 'Check PR comment limit before running'
        required: false
        type: boolean
        default: true
      comment-limit:
        description: 'Maximum number of comments before skipping review'
        required: false
        type: number
        default: 50
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  claude:
    name: "Claude Code Review"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Check PR comment limit
        if: inputs.check-comment-limit
        id: comment-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          COMMENT_LIMIT: ${{ inputs.comment-limit }}
        run: |
          TOTAL_COMMENTS=$(gh api graphql -f query='
          query {
            repository(owner: "'$REPO_OWNER'", name: "'$REPO_NAME'") {
              pullRequest(number: '$PR_NUMBER') {
                comments(last: 100) {
                  totalCount
                }
                reviewThreads(last: 100) {
                  totalCount
                }
              }
            }
          }' --jq '.data.repository.pullRequest.comments.totalCount + .data.repository.pullRequest.reviewThreads.totalCount')

          echo "total_comments=$TOTAL_COMMENTS" >> $GITHUB_OUTPUT
          if [ "$TOTAL_COMMENTS" -ge "$COMMENT_LIMIT" ]; then
            echo "âš ï¸ PR has reached ${COMMENT_LIMIT}-comment limit - skipping Claude review"
            echo "skip_review=true" >> $GITHUB_OUTPUT
          else
            echo "âœ“ Comment count: $TOTAL_COMMENTS (under ${COMMENT_LIMIT}-comment limit)"
            echo "skip_review=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Claude Code Review
        id: claude-review
        if: ${{ !inputs.check-comment-limit || steps.comment-check.outputs.skip_review == 'false' }}
        uses: anthropics/claude-code-action@v1
        timeout-minutes: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          track_progress: true
          use_sticky_comment: true
          claude_args: |
            --max-turns ${{ inputs.max-turns }}
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(markdownlint-cli2:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*)"
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Review this PR focusing on:
            - Security: Secrets management, input validation, access control
            - Code Quality: Standards compliance, error handling, readability
            - Maintainability: Modularity, proper documentation

            Priority levels for feedback:
            - ðŸ”´ Required: Security issues, breaking changes, major bugs
            - ðŸŸ¡ Suggested: Code quality improvements, optimizations
            - ðŸŸ¢ Optional: Style preferences, alternative approaches

            Use the MCP inline comment tool for specific code issues.
            Use gh pr comment to post an overall summary.
