name: Claude Code Review (Reusable)

on:
  workflow_call:
    inputs:
      max-turns:
        description: 'Maximum turns for Claude Code'
        required: false
        type: number
        default: 5
      timeout-minutes:
        description: 'Timeout for the Claude Code action'
        required: false
        type: number
        default: 5
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  claude:
    name: "Claude Code Review"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        timeout-minutes: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          track_progress: true
          use_sticky_comment: true
          claude_args: |
            --max-turns ${{ inputs.max-turns }}
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(markdownlint-cli2:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*)"
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Review this PR focusing on:
            - Security: Secrets management, input validation, access control
            - Code Quality: Standards compliance, error handling, readability
            - Maintainability: Modularity, proper documentation

            Priority levels for feedback:
            - 🔴 Required: Security issues, breaking changes, major bugs
            - 🟡 Suggested: Code quality improvements, optimizations
            - 🟢 Optional: Style preferences, alternative approaches

            Use the MCP inline comment tool for specific code issues.
            Use gh pr comment to post an overall summary.
