name: Markdown Lint (Reusable)

on:
  workflow_call:
    inputs:
      globs:
        description: 'Glob pattern for markdown files to lint'
        required: false
        type: string
        default: '**/*.md'
      fix:
        description: 'Auto-fix markdown issues'
        required: false
        type: boolean
        default: true
      validate-commands:
        description: 'Run command frontmatter validation script'
        required: false
        type: boolean
        default: false
      validation-script:
        description: 'Path to validation script'
        required: false
        type: string
        default: './scripts/validate-commands.sh'

jobs:
  markdownlint-cli2:
    name: "Lint Markdown Files"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate command frontmatter
        if: inputs.validate-commands
        run: ${{ inputs.validation-script }}

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: ${{ inputs.globs }}
          fix: ${{ inputs.fix }}
