# name: Terraform
#
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#
# jobs:
#   terraform:
#     name: 'Terraform'
#     runs-on: ubuntu-latest
#     timeout-minutes: 60
#
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#
#       - name: Terraform Init
#         run: terraform init
#
#       - name: Terraform Validate
#         run: terraform validate
#
#       - name: Terraform Plan
#         run: terraform plan -input=false